AutoDem/AutoDem/Models/AutosViewModels.cs
using AutoDem.DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AutoDem.Models
{
    public class AutoIndexViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Country { get; set; }
        public string PathToPhoto { get; set; }
    }


    public class SoldNewAutoViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public List<string> PathToPhotos { get; set; }
    }


    public class AutoDetailsViewModel
    {
        public int Id { get; set; }
        public int YearOfManufacture { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Color { get; set; }
        public DateTime DatePublication { get; set; } = DateTime.Now;
        public int Mileage { get; set; }
        public double EngineCapacity { get; set; }
        //Привід
        public string Drive { get; set; }
        //коробка передач
        public string Transmission { get; set; }
        public bool SoldOut { get; set; }
        public string ModelName { get; set; }
        public string BrandName { get; set; }

        //хешбек, седан...
        public string TypeAuto { get; set; }
        public string FuelType { get; set; }
        public string Country { get; set; }
        public List<string> AdditionalOptions { get; set; }
        public List<Comment> Comments { get; set; }
        public List<string> PathToPhotos { get; set; }
        public List<SoldNewAutoViewModel> LastSoldCars { get; set; }
        public List<SoldNewAutoViewModel> LastNewCars { get; set; }

    }
    public class CommentViewModel
    {
        [Display(Name = "Ім'я")]
        public string AuthorFName { get; set; }
        [Required(ErrorMessage = "Обов'язково заповнити")]
        [Display(Name = "Електронна адреса")]
        [EmailAddress(ErrorMessage = "Некоректна адреса")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Обов'язково заповнити")]
        [Display(Name = "Повідомлення")]
        public string Body { get; set; }
        public int IdAuto { get; set; }
    }
}

AutoDem/AutoDem/Controllers/AutosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoDem.DAL;
using AutoDem.Models;
using CaptchaMvc.HtmlHelpers;

namespace AutoDem.Controllers
{
    public class AutosController : Controller
    {
        public AutosController()
        {
            this.ViewData["MainLayoutViewModel"] = db.Repository<Service>().GetAll()?.Select(x => x.Title).ToList();
        }
        private GenericUnitOfWork db = new GenericUnitOfWork();

        // GET: Autos
        public async Task<ActionResult> Index()
        {
            List<AutoIndexViewModel> list = new List<AutoIndexViewModel>();

            var tmp = await db.Repository<Auto>().GetAllAsync();

            foreach (var item in tmp)
            {
                list.Add(new AutoIndexViewModel()
                {
                    Country = item.Country.Name,
                    PathToPhoto = item.PhotoAutos.FirstOrDefault() == null ? "" : item.PhotoAutos.First().PathToPhoto,
                    Name = item.Model?.Name + " " + item.Type?.Name + " " + item.YearOfManufacture,
                    ShortDescription = (item.Description.Split().Take(15).Aggregate("", (a, b) => a + " " + b))+"...",
                    Id = item.Id
                });
            }

            return View(list);
        }

        // GET: Autos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Auto auto = await db.Repository<Auto>().FindByIdAsync(id);

            if (auto == null)
            {
                return HttpNotFound();
            }

            List<SoldNewAutoViewModel> soldAutos = new List<SoldNewAutoViewModel>();

            var list = (await db.Repository<Auto>().FindAllAsync(x => x.SoldOut == true))?.OrderByDescending(x => x.DatePublication).Take(4).ToList();

            foreach (var x in list)
            {
                soldAutos.Add(new SoldNewAutoViewModel()
                {
                    Id = x.Id,
                    Name = $"{x.Model.Brand?.Name}  {x.Model?.Name} {x.YearOfManufacture}",
                    PathToPhotos = x.PhotoAutos.Count == 0 ? new List<string>(new string[] { "/images/Autos/empty.jpg", "/images/Autos/empty.jpg" }) : x.PhotoAutos?.Count >= 2 ? x.PhotoAutos.Select(path => path.PathToPhoto).Take(2).ToList() : new List<string>(new string[] { x.PhotoAutos[0].PathToPhoto, x.PhotoAutos[0].PathToPhoto }),
                    Price = x.Price
                });

            }

            List<SoldNewAutoViewModel> newCars = new List<SoldNewAutoViewModel>();

            list = (await db.Repository<Auto>().FindAllAsync(x => x.SoldOut == false))?.OrderByDescending(x => x.DatePublication).Take(4).ToList();

            foreach (var x in list)
            {
                newCars.Add(new SoldNewAutoViewModel()
                {
                    Id = x.Id,
                    Name = $"{x.Model.Brand?.Name}  {x.Model?.Name} {x.YearOfManufacture}",
                    PathToPhotos = x.PhotoAutos.Count == 0? new List<string>(new string[] { "/images/Autos/empty.jpg", "/images/Autos/empty.jpg" }) :  x.PhotoAutos?.Count >= 2 ? x.PhotoAutos.Select(path => path.PathToPhoto).Take(2).ToList() : new List<string>(new string[] { x.PhotoAutos[0].PathToPhoto, x.PhotoAutos[0].PathToPhoto }),
                    Price = x.Price
                });
            }


            AutoDetailsViewModel details = new AutoDetailsViewModel()
            {
                Color = auto.Color,
                Country = auto.Country?.Name,
                DatePublication = auto.DatePublication != null ? auto.DatePublication : DateTime.Now ,
                Description = auto.Description,
                Drive = auto.Drive,
                FuelType = auto.FuelType?.Name,
                Mileage = auto.Mileage,
                BrandName = auto.Model?.Brand?.Name,
                ModelName = auto.Model?.Name,
                SoldOut = auto.SoldOut,
                Price = auto.Price,
                Transmission = auto.Transmission,
                YearOfManufacture = auto.YearOfManufacture,
                TypeAuto = auto.Type?.Name,
                EngineCapacity = auto.EngineCapacity,
                PathToPhotos = auto.PhotoAutos?.Select(x => x.PathToPhoto).ToList(),
                AdditionalOptions = auto.AdditionalOptions?.Select(x => x.characteristic).ToList(),
                Comments = auto.Comments,
                Id = auto.Id,
                LastSoldCars = soldAutos,
                LastNewCars = newCars
            };

            return View(details);
        }

        [HttpPost]
        public async Task<ActionResult> Comment(CommentViewModel model)
        {
            if (!this.IsCaptchaValid("Captcha is not valid"))
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            if (!ModelState.IsValid) //data validation failed
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }

            DAL.Comment comm = new Comment()
            {
                AuthorName = Server.HtmlEncode(model.AuthorFName),
                Email = Server.HtmlEncode(model.Email),
                Body = Server.HtmlEncode(model.Body),
                Auto = await db.Repository<Auto>().FindByIdAsync(model.IdAuto)
            };

            await db.Repository<Comment>().AddAsync(comm);
            await db.SaveAsync();


            return Json(new { success = true }, JsonRequestBehavior.AllowGet);


        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoDem/AutoDem/Views/Autos/Create.cshtml
@model AutoDem.DAL.Auto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Auto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.YearOfManufacture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfManufacture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfManufacture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePublication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePublication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatePublication, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mileage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mileage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mileage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EngineCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngineCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EngineCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Drive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Drive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transmission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Transmission, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Transmission, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoldOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.SoldOut)
                    @Html.ValidationMessageFor(model => model.SoldOut, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoDem/AutoDem/Views/Autos/Details.cshtml
@model AutoDem.Models.AutoDetailsViewModel
@using CaptchaMvc.HtmlHelpers

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript" src="~/Scripts/customjs/auto_jquery-2.1.4.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script type="application/x-javascript">
    addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
           function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--//tags -->

<link rel="stylesheet" href="~/Content/Auto/auto_flexslider.css" type="text/css" media="screen" />
<link href="~/Content/Auto/auto_style.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/Content/Auto/auto_font-awesome.css" rel="stylesheet">
<link href="~/Content/Auto/auto_easy-responsive-tabs.css" rel='stylesheet' type='text/css' />
@*<link href="~/Content/bootstrap-rating.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-rating/bootstrap-rating.min.js"></script>*@
<!-- //for bootstrap working -->
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
<!-- header -->

<div class="gtco-loader"></div>
<!-- banner-bootom-w3-agileits -->
<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/images/main_background.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row row-mt-15em">
            <div class="col-md-12 mt-text text-center animate-box" data-animate-effect="fadeInUp">
                <h1>Тут є<strong> доступна машина</strong></h1>
                <h2>просто вона доступна...</h2>
            </div>
        </div>
    </div>
</header>
<div class="banner-bootom-w3-agileits" style="position:relative;top:20px;">
    <div class="container">
        <!---728x90--->

        <div class="col-md-4 single-right-left ">
            <div class="grid images_3_of_2">
                <div class="flexslider">

                    <ul class="slides">
                        @foreach (var i in Model.PathToPhotos)
                        {
                            <li data-thumb="@i">
                                <div class="thumb-image"> <img src="@i" data-imagezoom="true" class="img-responsive"> </div>
                            </li>
                        }
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-md-8 single-right-left simpleCart_shelfItem">
            <h3>@(Model.BrandName + "  " + Model.ModelName + "  " + Model.YearOfManufacture)</h3>
            <p><span class="item_price">$@Model.Price</span> <del>- $@(Model.Price * 1.2m)</del></p>
            <div class="description">
                <h5>Опис автомобіля</h5>
                <p>@Html.Raw(Model.Description)</p>

            </div>
        </div>
        <div class="clearfix"> </div>
        <!---728x90--->
        <!-- /new_arrivals -->
        <div class="responsive_tabs_agileits">
            <div id="horizontalTab">
                <ul class="resp-tabs-list">
                    <li>Опис</li>
                    <li>Відгуки</li>
                    <li>Додаткова інформація</li>
                </ul>
                <div class="resp-tabs-container">
                    <!--/tab_one-->
                    <div class="tab1">

                        <div class="single_page_agile_its_w3ls">
                            <h6>Заголовок</h6>
                            <p>@(Model.BrandName + "  " + Model.ModelName + "  " + Model.YearOfManufacture)</p>
                            <p>Пробіг : @Model.Mileage</p>
                            <p>Тип : @Model.TypeAuto</p>
                            <p>Об'єм двигуна : @Model.EngineCapacity</p>
                            <p>Тип Палива : @Model.FuelType</p>
                            <p>Привід : @Model.Drive</p>
                            <p>Коробка передач : @Model.Transmission</p>



                        </div>
                    </div>
                    <!--//tab_one-->
                    <div class="tab2">

                        <div class="single_page_agile_its_w3ls">

                            @foreach (var comm in Model.Comments)
                            {
                                <div class="bootstrap-tab-text-grids">
                                    <div class="bootstrap-tab-text-grid">
                                        <div class="bootstrap-tab-text-grid-left">
                                            <img src="/images/avatar.png" alt=" " class="img-responsive">
                                        </div>
                                        <div class="bootstrap-tab-text-grid-right">
                                            <ul>
                                                <li><a href="#">@comm.AuthorName</a></li>
                                                @*<li>Рейтинг : @Html.BootstrapRating(m => (double)(comm.Rating))</li>*@
                                            </ul>
                                            <p>
                                                @comm.Body
                                            </p>
                                        </div>
                                        <div class="clearfix"> </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="tab3">

                        <div class="single_page_agile_its_w3ls">
                            <h6>Додаткова інформація</h6>
                            @foreach (var i in Model.AdditionalOptions)
                            {
                                <p>@i</p>
                            }

                        </div>
                    </div>
                </div>
            </div>
            <div class="add-review">
                <h4>Добавити відгук</h4>
                @using (Ajax.BeginForm("Comment", "Autos", null, new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "OnSuccess",
    }, new
    {
        enctype = "multipart/form-data"
    }))
    {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <input type="text" name="AuthorFName" id="AuthorFName" placeholder="Ім'я" style="max-width:100%">
            <input type="email" name="Email" id="Email" size="100" placeholder="Пошта" style="max-width:100%"><br>
            <textarea name="Body" id="Body" placeholder="Повідомлення" cols="200" style="max-width:100%"></textarea><br>
            <input type="hidden" name="IdAuto" id="IdAuto" value="@Model.Id">
            @Html.MathCaptcha();
            <input type="submit" value="Надіслати"> <div id="mstatus"></div>
}
            </div>
        </div>



        <div class="w3_agile_latest_arrivals">
            <h3 class="wthree_text_info">Нові <span> автомобілі</span></h3>

            @foreach (var item in Model.LastNewCars)
            {
                <div class="col-md-3 product-men single">
                    <div class="men-pro-item simpleCart_shelfItem">
                        <div class="men-thumb-item">
                            <img src="@item.PathToPhotos[0]" alt="" class="pro-image-front">
                            <img src="@item.PathToPhotos[1]" alt="" class="pro-image-back">
                            <div class="men-cart-pro">
                                <div class="inner-men-cart-pro">
                                    @Html.ActionLink("Переглянути", "Details", new { id = item.Id }, new { @class = "link-product-add-cart" })
                                </div>
                            </div>
                            <span class="product-new-top">New</span>

                        </div>
                        <div class="item-info-product ">
                            <h4>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</h4>
                            <div class="info-product-price">
                                <span class="item_price">$@(item.Price * 1.2m)</span>
                                <del>$@item.Price</del>
                            </div>
                        </div>
                    </div>
                </div>
            }

            <div class="clearfix"> </div>

        </div>




        <div class="w3_agile_latest_arrivals">
            <h3 class="wthree_text_info">Останні <span>Продані автомобілі</span></h3>

            @foreach (var item in Model.LastSoldCars)
            {
                <div class="col-md-3 product-men single">
                    <div class="men-pro-item simpleCart_shelfItem">
                        <div class="men-thumb-item">
                            <img src="@item.PathToPhotos[0]" alt="" class="pro-image-front">
                            <img src="@item.PathToPhotos[1]" alt="" class="pro-image-back">
                            <div class="men-cart-pro">
                                <div class="inner-men-cart-pro">
                                    @Html.ActionLink("Переглянути", "Details", new { id = item.Id }, new { @class = "link-product-add-cart" })
                                </div>
                            </div>
                            <span class="product-new-top">Sold</span>

                        </div>
                        <div class="item-info-product ">
                            <h4>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</h4>
                            <div class="info-product-price">
                                <span class="item_price">$@(item.Price * 1.2m)</span>
                                <del>$@item.Price</del>
                            </div>
                        </div>
                    </div>
                </div>
            }

            <div class="clearfix"> </div>

        </div>










    </div>
</div>


@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/index")

<script src="~/Scripts/customjs/auto_minicart.min.js"></script>
<script>
    // Mini Cart
    paypal.minicart.render({
        action: '#'
    });

    if (~window.location.search.indexOf('reset=true')) {
        paypal.minicart.reset();
    }
</script>

<!-- //cart-js -->
<!-- single -->
<script src="~/Scripts/customjs/auto_imagezoom.js"></script>
<!-- single -->
<!-- script for responsive tabs -->
<script src="~/Scripts/customjs/auto_easy-responsive-tabs.js"></script>
<script>
    $(document).ready(function () {
        $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion
            width: 'auto', //auto or any width like 600px
            fit: true,   // 100% fit in a container
            closed: 'accordion', // Start closed if in accordion view
            activate: function (event) { // Callback function if tab is switched
                var $tab = $(this);
                var $info = $('#tabInfo');
                var $name = $('span', $info);
                $name.text($tab.text());
                $info.show();
            }
        });
        $('#verticalTab').easyResponsiveTabs({
            type: 'vertical',
            width: 'auto',
            fit: true
        });
    });
</script>
<!-- FlexSlider -->
<script src="~/Scripts/customjs/auto_jquery.flexslider.js"></script>
<script>
    // Can also be used with $(document).ready()
    $(window).load(function () {
        $('.flexslider').flexslider({
            animation: "slide",
            controlNav: "thumbnails"
        });
    });
</script>
<!-- //FlexSlider-->
<!-- //script for responsive tabs -->
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="~/Scripts/customjs/auto_move-top.js"></script>
<script type="text/javascript" src="~/Scripts/customjs/auto_jquery.easing.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
        });
    });
</script>
<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function () {
        /*
            var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
            };
        */



    });
</script>
<!-- //here ends scrolling icon -->
<!-- for bootstrap working -->
<script type="text/javascript">

    function OnSuccess(data) {
        if (data.success == true)
            document.getElementById("mstatus").innerHTML = "Повідомлення відправлено!";
        else {
            document.getElementById("mstatus").innerHTML = "Помилка відправлення!";
        }
        location.reload();
    }
</script>

AutoDem/AutoDem/Views/Autos/Index.cshtml
@model List<AutoDem.Models.AutoIndexViewModel>
@using System.Text.RegularExpressions
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner" style="background-image: url(/images/img_bg_4.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row row-mt-15em">
            <div class="col-md-7 mt-text text-left animate-box" data-animate-effect="fadeInUp">
                <h1>Наше <strong>Портфоліо</strong></h1>
                <h2>Far far away, behind the word mountains, far from the countries Vokalia.</h2>
            </div>
        </div>
    </div>
</header>




<div class="gtco-section gtco-gray-bg">
    <div class="gtco-container">
        <div class="row">

            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="@(Url.Action("Details", "Autos", new {id = Model[i].Id}))" class="gtco-card-item">
                        <figure>
                            <div class="overlay"><i class="ti-plus"></i></div>
                            <img src="@Model[i].PathToPhoto" alt="Image" class="img-responsive" style="width:100%">
                        </figure>
                        <div class="gtco-text">
                            <h2>@Model[i].Name</h2>
                            <p>@Regex.Replace(Model[i].ShortDescription, "(<(.|\n)*?>|&nbsp;)", string.Empty)</p>
                            <p class="gtco-category"><span>@Model[i].Country</span></p>@*, <span>Branding</span>, <span>Illustrator</span>*@
                        </div>
                    </a>
                </div>
            }

            <div class="clearfix visible-lg-block visible-md-block"></div>
            <div class="clearfix visible-sm-block"></div>
        </div>
    </div>
</div>



<div class="gtco-cover gtco-cover-sm" style="background-image: url(/images/img_bg_1.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container text-center">
        <div class="display-t">
            <div class="display-tc">
                <h1>Ми надаємо високоякісні послуги, які, точно, вам сподобаються!</h1>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/index")

AutoDem/AutoDem/Views/Autos/_CommentForm.cshtml
@model AutoDem.Models.CommentViewModel

@using (Html.BeginForm("Comment", "Autos", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.EditorFor(m => m.AuthorFName, new { htmlAttributes = new { placeholder = "Ваше ім'я", style = "max-width:100%" } })
    @Html.ValidationMessageFor(m => m.AuthorFName, "", new { @class = "text-danger" })
    @Html.EditorFor(m => m.Email, new { htmlAttributes = new {  placeholder = "Ваша ел. адреса", style = "max-width:100%" } })
    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
    @Html.TextAreaFor(model => model.Body, new {@cols = 30, @rows = 10, @placeholder = "Повідомлення", @style = "max-width:100%" })
    @Html.ValidationMessageFor(m => m.Body, "", new { @class = "text-danger" })
    <input type="submit" value="Надіслати">
}